# Generated by Django 2.0.13 on 2019-12-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='badanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_badania', models.DateTimeField(verbose_name='data badania')),
                ('status', models.BooleanField(default=False)),
                ('ważnosc_badania', models.DateTimeField(verbose_name='Data końca ważności')),
            ],
        ),
        migrations.CreateModel(
            name='diagnosta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('telefon', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='pojazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('numer_rejestracyjny', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='klient',
            name='pojazd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacjaDiagnostyczna_app.pojazd'),
        ),
        migrations.AddField(
            model_name='diagnosta',
            name='pojazd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacjaDiagnostyczna_app.pojazd'),
        ),
        migrations.AddField(
            model_name='badanie',
            name='pojazd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacjaDiagnostyczna_app.pojazd'),
        ),
    ]
