# Generated by Django 2.0.13 on 2020-01-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StacjaDiagnostyczna_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badanie',
            old_name='ważnosc_badania',
            new_name='waznosc_badania',
        ),
    ]
